### PR TITLE
Issue/#129  update new header component

### LINKED ISSUE #129: Update New Header Compontents
Update the new Header components to look like the design in the current, live site:  https://ramsayinnovations.com/

# Current

image

* Logo too small
* Need to add container padding
* Font Size & font weight of menu items

### PR DESCRIPTION
**Pull request by MaksymTaratuta55**
Closes #129

### CODE REVIEW

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, could you please give me Vercel details?

**Comment by MaksymTaratuta55** [comment]
Fixed conflicts

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, could you please send me vercel error message?

**Comment by MaksymTaratuta55** [comment]
> @thecodeclimber, could you please send me vercel error message?

Fixed :)

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

glad to hear it.  

With that said -- there is a warning.  Don't know if it is significant, but I'll post it just in case:

```

15:04:44.226 | warning " > @emotion/babel-plugin@11.1.2" has unmet peer dependency "@babel/core@^7.0.0".
-- | --
15:04:44.226 | warning "@emotion/css > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
15:04:44.228 | warning " > react-scroll@1.8.1" has incorrect peer dependency "react@^15.5.4 \|\| ^16.0.0".
15:04:44.228 | warning " > react-scroll@1.8.1" has incorrect peer dependency "react-dom@^15.5.4 \|\| ^16.0.0".
15:04:44.228 | warning " > styled-components@5.2.1" has unmet peer dependency "react-is@>= 16.8.0".


```

**Pull request merged**
