### PR TITLE
V1.0.1

### PR DESCRIPTION
**Pull request by MaksymTaratuta55**
Patch with hotfixes

### CODE REVIEW

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, could you please merge it?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

There are three more changes that we have to make:

1. We need to add a `Contact Us` link to the mobile menu?
2. Please remove the background patterns (right and left) AND the isomorphic graphic from the hero section in MOBILE view
image

3. Please remove background pattern from bio section
image

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, updated

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Thanks for making those changes.  


Also, a few more changes:

### FIRST CHANGE

* Can you please fix up the hero section on the Home page for the tablet view so that it looks like the mobile view.  I.e., this is how the hero section currently looks:  

image

Please have it look like this:  

image

I.e., remove the background patterns and the isomorphic icon.

### SECOND CHANGE

* Please fix the cards for the Ramsay Advisor section in the tablet view:

image

They should look like the cards in the Ramsay Method and Ramsay Commitment sections:
image

### THIRD CHANGE

* Please remove the blue line in the Bio section for mobile and tablet view.  
image


### FOURTH CHANGE

* Please remove the RIGHT side pattern lines in the CTA section in the mobile and tablet views:

image


Thanks.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Another couple of changes.

### FIRST CHANGE

We need to change the blurb on `/contact/ -- i.e., this page:  https://ramsay-site-8sh7mbavc-ramsay.vercel.app/contact/

* CURRENT:  `In order to help you as quickly as possible, please provide a little more information.` 
* NEW:  `Fill out the form below and we'll get back to you soon`

### SECOND CHANGE

We need to change the Title on `/contact/step-2` -- i.e., this page:  https://ramsay-site-8sh7mbavc-ramsay.vercel.app/contact/step-2

* CURRENT:  `Contact Us` 
* NEW:  `Additional Info`

**Review by thecodeclimber — APPROVED** [review]

**Pull request merged**
