### PR TITLE
Revert "Revert "#158  code the thank you & error pages""

### PR DESCRIPTION
**Pull request by MaksymTaratuta55**
Reverts ramsayinnovations/ramsay-site#160

### CODE REVIEW

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I've reverted it. This branch is for review now

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I've fixed https://github.com/ramsayinnovations/ramsay-site/pull/159#issuecomment-779753077

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, updated

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

We still need to make some stylistic changes to the Select Field.  Please take a look:  https://www.loom.com/share/efc4dc7f113142f1a69809f6390976e4

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, the color is the same as in inputs when you type something because it shows a selected option, not a placeholder

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

There is a new stylistic change that we have to add.  Here is a video about it:  https://www.loom.com/share/cc11df4dbec54254a1c466c7706079d2

Here is the Figma link:  https://www.figma.com/file/w1Qm5ofwF3DA1lAfjYsbLG/Ramsay-Innovations-Copy?node-id=7714%3A1752


I know this is not 100% related -- but there are just a few minor changes that we have to make -- and I figure that we can just add them on here rather then make a whole new user story out of them.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Okay -- but can we still have the color and font-size the same as the other input fields?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I mean when the user doesn't input other fields it could seem as incorrect but when the user put data in other fields everything is ok
Screenshot 2021-02-17 at 16 07 56
Screenshot 2021-02-17 at 16 08 09

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

We need to update the fields for the two different pages.  

### First Page: `/contact`

* Add `Message` field below the `Email` field


### Second Page: `/contact/more`

* Move `Title` Input field to top 

* Make `Phone` Full Width (100%)

* Make `Number of Employees` Full Width (100%)

* Add placeholder text for select field
   * Text: `Reason for Getting in Touch` 
   * Note: this is NOT a selectable option, just the text that appears when you see the form. 
     I believe you do by setting `value=""`

* Options for select field (each option should have `text-transform: capitalize`):
  * `Learn how to grow your company faster`
  * `Become a Growth Advisor`
  * `Become an employee`
  * `Join our referral program`
  * `Become a vendor`
  * `Other`

* Remove `Message` field

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, updated, bug with styles still in progress

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, updated with https://github.com/ramsayinnovations/ramsay-site/pull/161#issuecomment-780579026

**Comment by thecodeclimber** [comment]
I don't know if you are still working on this, but I'm still having a problem with the success page -- here is a screen shot:

image


Also, let's get rid of those two dots -- I don't think they work.  I.e., these:





Let's also have the `Phone` & `Number of Employees` fields be side by side again

Finally, what do you think of the following:

* Having the `Email` field be of `type="email"
* Having the `Number of Employees` field be of `type="number"

Perhaps this is not necessary.  What do you think?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I've fixed that bug with styles

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, updated, you can test all now

**Pull request merged**
