### PR TITLE
Feature/temp google tag manager

### PR DESCRIPTION
**Pull request by thecodeclimber**
@MaksymTaratuta55 
Please do one final review before I merge this into main.  

Thanks.

### CODE REVIEW

**Review by MaksymTaratuta55 — APPROVED** [review]

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I approved but git shows a conflict

**Comment by thecodeclimber** [comment]
Here is a screen shot from vs code about this file:

image

what should i chose?

**Comment by MaksymTaratuta55** [comment]
What did you do?

**Comment by MaksymTaratuta55** [comment]
It seems if you want to stay this file you should press "keep our version". If you want to delete this file, press 'delete'

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Can you take are of the merge conflicts?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Can you take of this conflict?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Please make this a priority.  I.e., before anything else we need to get this up and working.  Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, sure, I'll try

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, fixed

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Thanks.

**Pull request merged**
