### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by MaksymTaratuta55**
https://github.com/ramsayinnovations/ramsay-site/pull/188#issuecomment-787994104
https://github.com/ramsayinnovations/ramsay-site/pull/188#issuecomment-788041736

### CODE REVIEW

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Almost there:

### ONE

We still need to get rid of the blue line in the Bio section on mobile and tablet view:

* Bio Section:  https://ramsay-site-rdcmzs6d2-ramsay.vercel.app/
* Blue line:

image


### TWO

We need the contact form title and blurb to be the same on mobile, tablet & desktop view.  Right now the blurb switches when on tablet or mobile view.

### THREE

We need the right blurb for each step of the form:

* FIRST STEP:  `Fill out the form below and we'll get back to you soon`
* SECOND STEP:  `In order to help you as quickly as possible, please provide a little more information.`

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, updated

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

There are still more changes -- here are some videos:

### HERO SECTION

https://www.loom.com/share/f8c796a731ea4034a85a869c18c3c17c

### CALL TO ACTION SECTION

https://www.loom.com/share/236d81c994f7425ba5552e479df69cb8

### CONTACT US PAGE

https://www.loom.com/share/d8b34743c8044db39f0e7448e9267e3e

### STEP 2 FORM

https://www.loom.com/share/2059ae99610a448a815b8d0cc451ecec

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, updated

**Pull request merged**
