### PR TITLE
Issue/#128  use google tag manager component in  app.js

### LINKED ISSUE #128: Use GoogleTagManager Component in _app.js
Please note how the `GoogleTagManager` component is used here:  https://github.com/vercel/next.js/blob/canary/examples/with-google-tag-manager/pages/_app.js

We also need to wrap `<Component {...pageProps} />` in `_app.jsx` with the `GoogleTagManager` component (this should be done in the `develop--clone` branch)

**Note:** this issue needs to be done after we take care of issue #126.

### PR DESCRIPTION
**Pull request by MaksymTaratuta55**
Closes #128

### CODE REVIEW

**Comment by MaksymTaratuta55** [comment]
Should be merged after #126

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

I have merged #134.  However, it still says that All checks have failed.  Please let me know how to proceed.  Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I haven't access to the Vercel details https://vercel.com/ramsay/ramsay-site/mjuzsgzzz to check what is the problem

**Comment by thecodeclimber** [comment]
Here is the build log from vercel:

```
11:53:31.178 | Cloning github.com/ramsayinnovations/ramsay-site (Branch: issue/#128--Use-GoogleTagManager-Component-in-_app.js, Commit: df39b5f)
-- | --
11:53:32.820 | Cloning completed in 1642ms
11:53:32.823 | Analyzing source code...
11:53:33.548 | Installing build runtime...
11:53:34.060 | Build runtime installed: 511.632ms
11:53:34.514 | Looking up build cache...
11:53:34.644 | Build cache found. Downloading...
11:53:35.756 | Build cache downloaded [33.97 MB]: 1111.458ms
11:53:36.222 | Installing dependencies...
11:53:36.445 | yarn install v1.22.4
11:53:36.503 | [1/4] Resolving packages...
11:53:36.800 | success Already up-to-date.
11:53:36.804 | Done in 0.36s.
11:53:36.819 | Running "yarn run build"
11:53:37.082 | yarn run v1.22.4
11:53:37.104 | $ next build
11:53:37.825 | info  - Creating an optimized production build...
11:53:45.844 | Failed to compile.
11:53:45.844 | ModuleNotFoundError: Module not found: Error: Can't resolve '../lib/gtm' in '/vercel/workpath0/src/components/elements'
11:53:45.844 | > Build error occurred
11:53:45.845 | Error: > Build failed because of webpack errors
11:53:45.845 | at /vercel/workpath0/node_modules/next/dist/build/index.js:15:918
11:53:45.845 | at runMicrotasks (<anonymous>)
11:53:45.845 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
11:53:45.845 | at async /vercel/workpath0/node_modules/next/dist/build/tracer.js:1:525
11:53:45.867 | error Command failed with exit code 1.
11:53:45.867 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
11:53:45.877 | Error: Command "yarn run build" exited with 1
11:53:48.048 | Done with "package.json"
```

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Just a reminder to please take care of this as soon as you can.  Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, fixed

**Pull request merged**
