### PR TITLE
Issue/#36  fix blurry logo on mobile

### PR DESCRIPTION
**Pull request by kirti75waytech**
Hi ! @MaksymTaratuta55 @thecodeclimber I have resolved issue #36 in this PR. Please review it and let me know if another modifications we need. Thanks

### CODE REVIEW

**Comment by thecodeclimber** [comment]
I have two questions before accepting this pull request.

### First Question

The site does NOT look right when I take a look at it.  See this video for details:  https://www.loom.com/share/8b408ba07cf246fdbba709ed9c262080

### Second Question

There are a lot of conflicts with this branch as noted above.  Here is a screenshot:

image


It seems to me that we should first resolve these conflicts before we accept this pull request.  Do you agree?

**Comment by kirti75waytech** [comment]
> I have two questions before accepting this pull request.
> 
> ### First Question
> The site does NOT look right when I take a look at it. See this video for details: https://www.loom.com/share/8b408ba07cf246fdbba709ed9c262080
> 
> ### Second Question
> There are a lot of conflicts with this branch as noted above. Here is a screenshot:
> 
> image
> 
> It seems to me that we should first resolve these conflicts before we accept this pull request. Do you agree?

Hi @thecodeclimber Sorry, I don't know Why is this happening, But when I am locally running this branch I can see the working website. And yeah, I would also suggest to first resolve all the conflicts and then we should move ahead.
Thanks

**Comment by thecodeclimber** [comment]
@kirti75waytech 

Okay, please keep me updated.  Thanks.

**Comment by thecodeclimber** [comment]
@kirti75waytech 

I see that you have moved this over to PR #78.  We can continue the conversation there :).

**Pull request closed without merging**
