### PR TITLE
Issue/#52  create own component for input with error

### PR DESCRIPTION
**Pull request by kirti75waytech**
Hi! @MaksymTaratuta55 and @thecodeclimber, I have created a common InputFeild component as per issue: #52 in this PR and used it in contact-us page & call-to-action page. Please let me know If any modification required.
Thanks

### CODE REVIEW

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, sorry, I can't approve this PR. I would like another implementation for this component. If you don't mind I'll add it with my PR for #60 and you'll review it?

**Comment by kirti75waytech** [comment]
> Yes, @MaksymTaratuta55, You can merge this PR #70 with your code. Please let me If any other changes are required.

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, I implemented it yesterday and you can check in #72

**Comment by kirti75waytech** [comment]
> @kirti75waytech, I implemented it yesterday and you can check in #72

@MaksymTaratuta55 I have reviewed the PR #72. it looks good to me, we can merge it.

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, do you mind if I close this PR?

**Comment by thecodeclimber** [comment]
@kirti75waytech 

Can we close this PR?

**Comment by kirti75waytech** [comment]
> @kirti75waytech
> 
> Can we close this PR?

@thecodeclimber Yes, we can close this PR, as its code is utilised by @MaksymTaratuta55 in his PR #72.

**Pull request closed without merging**
